-- Create the 'service_activation' table first
CREATE TABLE service_activation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    description VARCHAR(255),
    service_type VARCHAR(255),
    state VARCHAR(255)
);

-- Create the 'feature' table
CREATE TABLE feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
    name VARCHAR(255),                                      -- Name of the feature
    service_activation_id BIGINT,                           -- Foreign key to 'service_activation'
    FOREIGN KEY (service_activation_id) REFERENCES service_activation(id)  -- Relationship
);

-- Create the 'feature_characteristic' table
CREATE TABLE feature_characteristic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
    name VARCHAR(255),                                      -- Name of the characteristic
    value_type VARCHAR(255),                                -- Type of value (e.g., string, number)
    feature_id BIGINT,                                     -- Foreign key to 'feature'
    FOREIGN KEY (feature_id) REFERENCES feature(id)  -- Relationship
);

-- Create the 'offer' table
CREATE TABLE offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
    offer_id VARCHAR(255),                                  -- Offer ID
    effective_date DATE,                                    -- Date the offer becomes effective
    expiry_date DATE,                                      -- Date the offer expires
    offer_cd VARCHAR(255),                                -- Offer code
    offer_sequence_number VARCHAR(255),                    -- Sequence number for the offer
    offer_type_cd VARCHAR(255),                            -- Type code for the offer
    name VARCHAR(255),                                    -- Name of the offer
    value_type VARCHAR(255),                              -- Type of value for the offer
    feature_characteristic_id BIGINT,                       -- Foreign key to 'feature_characteristic'
    FOREIGN KEY (feature_characteristic_id) REFERENCES feature_characteristic(id)  -- Relationship
);

-- Create the 'offer_parameter' table
CREATE TABLE offer_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
    parameter_cd VARCHAR(255),                              -- Parameter code
    parameter_name VARCHAR(255),                            -- Name of the parameter
    parameter_effective_date DATE,                          -- Effective date of the parameter
    parameter_expiry_date DATE,                             -- Expiry date of the parameter
    parameter_value_tx VARCHAR(255),                        -- Value of the parameter
    offer_id BIGINT,                                        -- Foreign key to 'offer'
    FOREIGN KEY (offer_id) REFERENCES offer(id)  -- Relationship
);

-- Create the 'related_party' table
CREATE TABLE related_party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
    id_value VARCHAR(255),                                  -- ID value of the related party
    role VARCHAR(255),                                    -- Role of the related party
    referred_type VARCHAR(255),                            -- Type of the referred party
    service_activation_id BIGINT,                           -- Foreign key to 'service_activation'
    FOREIGN KEY (service_activation_id) REFERENCES service_activation(id)  -- Relationship
);

-- Create the 'service_characteristic' table
--CREATE TABLE service_characteristic (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    name VARCHAR(255),
--    valuetype VARCHAR(255),
--    value VARCHAR(255),
--    service_activation_id BIGINT,
--    FOREIGN KEY (service_activation_id) REFERENCES service_activation(id)
--);
