server:
  port: 8085

spring:
  application:
    name: tmfsac-transaction
  datasource:
    url: jdbc:postgresql://pg-fd78062-gautam-db88.f.aivencloud.com:27747/tmf640_poswls?sslmode=require
    username: avnadmin
    password: AVNS_GVrfCPJv-yx1DSPusWb
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/activationdb
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
management:
  endpoint:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  shutdown:
    enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationinOpenState: 10000